/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        Cube: THREE.Mesh
        Cube_1: THREE.Mesh
        Cube_2: THREE.Mesh
        S: THREE.Mesh
        N: THREE.Mesh
    }
    materials: {
        Red: THREE.MeshStandardMaterial
        Blue: THREE.MeshStandardMaterial
        Metallic: THREE.MeshStandardMaterial
        Text: THREE.MeshStandardMaterial
    }
}

export function Magnet3D(props: JSX.IntrinsicElements['group'] & { orientation?: number }) {
    const { nodes, materials } = useGLTF('/articles/science_of_complexity/models/magnet.glb') as unknown as GLTFResult
    return (
        <group {...props} dispose={null} rotation={props.rotation || [0, props.orientation === 0 ? 0 : Math.PI, 0]}>
            <group scale={[0.763, 0.3, 1]}>
                <mesh castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials.Red} />
                <mesh castShadow receiveShadow geometry={nodes.Cube_1.geometry} material={materials.Blue} />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube_2.geometry}
                    material={materials.Metallic}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.S.geometry}
                material={materials.Text}
                position={[-0.007, 0.32, 1.556]}
                scale={[2.043, 1, 2.043]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.N.geometry}
                material={materials.Text}
                position={[-0.001, 0.32, -1.636]}
                rotation={[Math.PI, 0, Math.PI]}
                scale={[2.043, 1, 2.043]}
            />
        </group>
    )
}

useGLTF.preload('/articles/science_of_complexity/models/magnet.glb')
