/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        Cylinder: THREE.Mesh
        Cylinder_1: THREE.Mesh
    }
    materials: {
        Spin: THREE.MeshStandardMaterial
        Atom: THREE.MeshStandardMaterial
    }
}

export function Spin(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/articles/science_of_complexity/models/spin.glb') as unknown as GLTFResult
    return (
        <group {...props} dispose={null}>
            <mesh castShadow receiveShadow geometry={nodes.Cylinder.geometry} material={materials.Spin} />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_1.geometry}
                material={materials.Atom}
            />
        </group>
    )
}

useGLTF.preload('/articles/science_of_complexity/models/spin.glb')
