/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        Lattice_1: THREE.Mesh
        Lattice_2: THREE.Mesh
        Plane: THREE.Mesh
        Atoms: THREE.Mesh
        Spin: THREE.Mesh
    }
    materials: {
        Lattice: THREE.MeshStandardMaterial
        Background: THREE.MeshStandardMaterial
        Atom: THREE.MeshStandardMaterial
        Spin: THREE.MeshStandardMaterial
    }
}

export function SpinsLattice(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/articles/science_of_complexity/models/spins_lattice.glb') as unknown as GLTFResult
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Lattice_1.geometry}
                material={materials.Lattice}
                position={[1.729, 0.257, -8.117]}
                rotation={[0, -1.571, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Lattice_2.geometry}
                material={materials.Lattice}
                position={[3.342, 0.257, -6.733]}
                rotation={[Math.PI, 0, Math.PI]}
                scale={[1, 1, 0.869]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Atoms.geometry}
                material={materials.Atom}
                position={[3.355, 0.27, -8.13]}
                rotation={[0, -1.571, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Spin.geometry}
                material={materials.Spin}
                position={[3.577, 0.259, -8.298]}
                rotation={[0, -Math.PI / 2, 0]}
                scale={0.866}
            />
        </group>
    )
}

useGLTF.preload('/articles/science_of_complexity/models/spins_lattice.glb')
